language: php
php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0

dist: trusty
sudo: required

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls

notifications:
  email: false